FROM python:alpine3.7

RUN mkdir /src
WORKDIR /src
COPY requirements.txt /src/requirements.txt
COPY main.py /src/main.py
COPY version.py /src/version.py
RUN pip install -r /src/requirements.txt
CMD [ "python", "main.py" ]